### PR TITLE
docs(samples): add create_table_clustered code snippet

### LINKED ISSUE #290: Add create_table_clustered sample code
Add code snippet for creating clustered table.

### PR DESCRIPTION
**Pull request by ryanyuan**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #290  🦕

### CODE REVIEW

**Review by tswast — COMMENTED** [review]
Thanks for the contribution! Could you also add a test file to the samples directory?

**Comment by ryanyuan** [comment]
> Thanks for the contribution! Could you also add a test file to the samples directory?

Done.

PTAL. Cheers! @tswast

**Review by tswast — APPROVED** [review]

**Review by engelke — APPROVED** [review]
LGTM

**Comment by tswast** [comment]
@ryanyuan Thanks so much for the contribution. Just sent internal change 335690842 out for review to get this added to the cloud.google.com docs.

**Comment by ryanyuan** [comment]
> @ryanyuan Thanks so much for the contribution. Just sent internal change 335690842 out for review to get this added to the cloud.google.com docs.

Awesome! Thank you @tswast

**Pull request merged**
