### PR TITLE
docs: Revise update_table_expiration sample

### PR DESCRIPTION
**Pull request by thejaredchapman**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Towards #790 🦕

### CODE REVIEW

**Review by tswast — CHANGES_REQUESTED** [review]
Looks good! But let's update `docs/snippets.py` with a comment that we should delete the duplicate sample there once we update cloud.google.com.

**Review by tswast — APPROVED** [review]

**Comment by tswast** [comment]
@thejaredchapman I think we might want to rebase this just so we can fixup the CLA check.

Would love to see the commit for https://github.com/googleapis/python-bigquery/pull/1516 as part of this PR instead of as a second PR, too.

**Comment by meredithslota** [comment]
Manually applied the `cla: yes` label since it's related to a Xoogler contribution made during employment.

**Comment by tswast** [comment]
I've squashed all commits and re-pushed. I believe that should resolve the CLA issue.

**Pull request merged**
