### PR TITLE
chore: revert "feat: add always_use_jwt_access"

### PR DESCRIPTION
**Pull request by tseaver**
Reverts googleapis/python-bigquery#714

### CODE REVIEW

**Comment by tseaver** [comment]
I don't know if the release bot will be able to figure it out, but this PR should undo the need for #711.

**Review by jimfulton — APPROVED** [review]
Hoping I'm not missing something.

**Comment by plamut** [comment]
> Hoping I'm not missing something.

You are (were) not, reverting that unwanted change was the right thing to do. :+1:

**Review by plamut — COMMENTED** [review]
LGTM

**Pull request merged**
