### PR TITLE
docs(samples): table variable fix

### LINKED ISSUE #1286: Table variable correction in browse_table_data.py
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-bigquery/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Steps to reproduce

Table variable needs to be updated in "# Print row data in tabular format."

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

### PR DESCRIPTION
**Pull request by adhiggs**
Updated table variable in "# Print row data in tabular format." to point at the correct table_id.

Fixes https://github.com/googleapis/python-bigquery/issues/1286

### CODE REVIEW

**Comment by adhiggs** [comment]
Not sure how to get these checks to pass. Thoughts?

**Comment by steffnay** [comment]
Hey, @adhiggs, the `Client.list_rows` method accepts type `Union[Table, TableListItem, TableReference, str]` for this parameter, so I am not recognizing the reason for this change.

**Comment by adhiggs** [comment]
Hi @steffnay, looping you in on bugs related, stay tuned.

**Comment by adhiggs** [comment]
Hi @meredithslota , @steffnay ! Any updates on this item?

**Comment by adhiggs** [comment]
Hi @meredithslota , @steffnay ! Any updates on this item? The dependency is preventing me from closing a bug on my side.

**Review by parthea — APPROVED** [review]

**Comment by adhiggs** [comment]
Hi team! Is there anything blocking this item from being merged in?

**Review by shollyman — APPROVED** [review]

**Pull request merged**
