### PR TITLE
chore: force build

### PR DESCRIPTION
**Pull request by jimfulton**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by plamut** [comment]
FWIW, the failing system test should be fixed with [this commit](https://github.com/googleapis/python-bigquery/pull/740/commits/47e1a58aae81787346c32b65d82f06674b3433e4).

**Comment by jimfulton** [comment]
> FWIW, the failing system test should be fixed with [this commit](https://github.com/googleapis/python-bigquery/pull/740/commits/47e1a58aae81787346c32b65d82f06674b3433e4).

Interesting.  

Thanks.

I'm curious why it just started failing.

**Comment by jimfulton** [comment]
Closing, as this PR was to experiment with CI builds, because mine were failing. :)

**Comment by plamut** [comment]
> I'm curious why it just started failing.

One of the system test runs did not clean the resource after itself, and since all were using the same resource identifier, subsequent runs started failing.

Not 100% sure _why_ a test did not clean after itself, though. If I had to guess, it might be that a test was abruptly terminated midway, i.e. after creating a Taxonomy resource, but before cleaning it up? E.g. a local run that is terminated with a `KeyboardInterrupt` at just the wrong moment.

**Pull request closed without merging**
