### PR TITLE
docs: add samples from bigquery/cloud-client

### LINKED ISSUE #149: Add bigquery/cloud-client samples from the samples repo
A transition to the new code generator (#147) requires the code samples to be moved from the common samples repo to here.

### PR DESCRIPTION
**Pull request by plamut**
Samples from https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/bigquery/cloud-client

---
> **IMPORTANT:** When merging, use the **rebase and merge** option to preserve the samples commit history!
---

**NOTE:** There are also other [bigquery-related samples](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/bigquery) in the samples repo. If any others besides `cloud-client` need to be moved here, please let me know and I'll open additional PRs.

Closes #149.
Towards #147.

### CODE REVIEW

**Comment by plamut** [comment]
@steffnay Does this PR affect the announced changes to the existing BigQuery samples in the repo in any way?

IIRC the existing sample files will be renamed, and this PR only adds new snippets from the common samples repo, but nevertheless asking, just in case.

**Comment by plamut** [comment]
A few problems:
 - The new template (generated in a synth run) `docs/samples/AUTHORING_GUIDE.md` is not included anywhere, resulting in a docs warning (treated as error).
- IPython import error in `samples/snippets/jupyter_tutorial_test.py` for some reason.
- GOOGLE_CLOUD_PROJECT env variable not set (or the expected variable name needs to be changed in the generated snippets noxfile)

Are these known or are do we have to do a few other tweaks in the BQ library itself?

**Comment by busunkim96** [comment]
> * The new template (generated in a synth run) `docs/samples/AUTHORING_GUIDE.md` is not included anywhere, resulting in a docs warning (treated as error).

Ah, I think the logic in synthtool is getting confused because there's a link to`samples` inside the docs directory. The intended home for the `AUTHORING_GUIDE.md` is samples/AUTHORING_GUIDE.md.

It looks like there are already samples in this repo, anyone have context on what the relationship between https://github.com/googleapis/python-bigquery/tree/master/samples and the ones in python-docs-samples? @shollyman? 

> * IPython import error in `samples/snippets/jupyter_tutorial_test.py` for some reason.

No idea what's happening here, maybe a missing requirement?

> * GOOGLE_CLOUD_PROJECT env variable not set (or the expected variable name needs to be changed in the generated snippets noxfile)

I think if you delete `samples/snippets/noxfile_config.py` the default project will be used. (I might have borked the templates though, we can check once the samples sessions run against this PR).

**Comment by steffnay** [comment]
@plamut This should be fine. We can just include these files when we go through and check all the region tags/file names.

**Comment by plamut** [comment]
I'll re-visit this in a few days and compare the state of it with the steps outlined in the samples migration guide. IIRC separate Kokoro jobs from samples need to be created (via code re-gen).

Other than that, it's primarily moving the samples (with history) from the other repo, yes.

**Comment by plamut** [comment]
Closing in favor of #174.

(regenerated samples from scratch, although it appears that this also does not solve the CI failures)

**Pull request closed without merging**
