### PR TITLE
fix: load_table_from_dataframe for higher scale decimal

### LINKED ISSUE #1650: Client.load_table_from_dataframe() sometimes chooses invalid column type
#### Environment details

  - OS type and version: macOS 13
  - Python version: Python 3.10.7
  - pip version: pip 23.2
  - `google-cloud-bigquery` version:  3.11.4

#### Steps to reproduce

  1. Create a table with a `BIGNUMERIC` type column
  2. Use `Client.load_table_from_dataframe()` to load a column with the value `Decimal("0.12345678901234560000000000000000000000")`

#### Code example

```python
df = pd.DataFrame("TEST_COL", Decimal("0.12345678901234560000000000000000000000"))
with bigquery.Client(project=project, credentials=credentials) as client:
    load_job = client.load_table_from_dataframe(df, table_name)
    result = load_job.result()
```

#### Stack trace
```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "pyarrow/array.pxi", line 1044, in pyarrow.lib.Array.from_pandas
  File "pyarrow/array.pxi", line 316, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Rescaling Decimal128 value would cause data loss
```

#### Details

I poked around a bit, and I think I see the problem. To determine the column type you create an arrow table https://github.com/googleapis/python-bigquery/blob/1760e945d16163980027fecf21113cd77ddc35a1/google/cloud/bigquery/_pandas_helpers.py#L566 then lookup the type by type ID https://github.com/googleapis/python-bigquery/blob/1760e945d16163980027fecf21113cd77ddc35a1/google/cloud/bigquery/_pandas_helpers.py#L587
My test decimal value can be represented by an arrow 128-bit type
```python
>>>pyarrow.array(pd.DataFrame({"x": [Decimal('0.12345678901234560000000000000000000000')]})["x"]).type
Decimal128Type(decimal128(38, 38))
```
But AFAICT that has the same type ID as every other Decimal128Type, so it maps to "NUMERIC" in your lookup table: https://github.com/googleapis/python-bigquery/blob/1760e945d16163980027fecf21113cd77ddc35a1/google/cloud/bigquery/_pandas_helpers.py#L185
So when you convert to pyarrow before uploading, it tries to coerce using your hardcoded type for "NUMERIC" https://github.com/googleapis/python-bigquery/blob/1760e945d16163980027fecf21113cd77ddc35a1/google/cloud/bigquery/_pandas_helpers.py#L380
and fails because it needed `decimal128(38, 38)` to represent the value, but is given  `decimal128(38, 9)`.  I think you will need to detect if a 128 bit type can't fit in your NUMERIC subtype and upgrade those to BIGNUMERIC.

Hope that helps!

### PR DESCRIPTION
**Pull request by Gaurang033**
Fixes #1650

### CODE REVIEW

**Comment by Linchin** [comment]
@Gaurang033 please fix the test failures

**Comment by Gaurang033** [comment]
> @Gaurang033 please fix the test failures

not able to see logs for https://source.cloud.google.com/results/invocations/570f5627-61a7-4aa7-8f1d-76eabc56918f/targets

**Comment by Gaurang033** [comment]
> @Gaurang033 please fix the test failures

could you help me understand which test is failing. I tried checking in logs but couldn't find much information. 
https://source.cloud.google.com/results/invocations/570f5627-61a7-4aa7-8f1d-76eabc56918f/log

**Comment by Linchin** [comment]
Coverage test is failing (if I remember correctly, something else if failing too. I'll take a look after the test results are out.)
```
nox > coverage report --show-missing --fail-under=100
Name                                                         Stmts   Miss Branch BrPart  Cover   Missing
--------------------------------------------------------------------------------------------------------
google/cloud/bigquery/_helpers.py                              291      0    152      0   100%
google/cloud/bigquery/_http.py                                  16      0      0      0   100%
google/cloud/bigquery/_job_helpers.py                           94      0     20      0   100%
google/cloud/bigquery/_pandas_helpers.py                       360      1    193      1    99%   521
google/cloud/bigquery/_pyarrow_helpers.py                       27      0      4      0   100%
google/cloud/bigquery/_tqdm_helpers.py                          55      0     20      0   100%
google/cloud/bigquery/_versions_helpers.py                      76      0     20      0   100%
google/cloud/bigquery/client.py                                855      0    318      0   100%
google/cloud/bigquery/dataset.py                               383      0     95      0   100%
google/cloud/bigquery/dbapi/__init__.py                         30      0      0      0   100%
google/cloud/bigquery/dbapi/_helpers.py                        170      0     96      0   100%
google/cloud/bigquery/dbapi/connection.py                       37      0     14      0   100%
google/cloud/bigquery/dbapi/cursor.py                          179      0     64      0   100%
google/cloud/bigquery/dbapi/exceptions.py                       11      0      0      0   100%
google/cloud/bigquery/dbapi/types.py                            29      0      4      0   100%
google/cloud/bigquery/encryption_configuration.py               28      0      4      0   100%
google/cloud/bigquery/enums.py                                 117      0      0      0   100%
google/cloud/bigquery/exceptions.py                              5      0      0      0   100%
google/cloud/bigquery/external_config.py                       426      0     58      0   100%
google/cloud/bigquery/format_options.py                         44      0      0      0   100%
google/cloud/bigquery/iam.py                                     6      0      0      0   100%
google/cloud/bigquery/job/__init__.py                           35      0      0      0   100%
google/cloud/bigquery/job/base.py                              338      0     68      0   100%
google/cloud/bigquery/job/copy_.py                             106      0     20      0   100%
google/cloud/bigquery/job/extract.py                           100      0     14      0   100%
google/cloud/bigquery/job/load.py                              376      0     58      0   100%
google/cloud/bigquery/job/query.py                             775      0    146      0   100%
google/cloud/bigquery/magics/__init__.py                         2      0      0      0   100%
google/cloud/bigquery/magics/line_arg_parser/__init__.py         7      0      0      0   100%
google/cloud/bigquery/magics/line_arg_parser/exceptions.py       5      0      0      0   100%
google/cloud/bigquery/magics/line_arg_parser/lexer.py           29      0      4      0   100%
google/cloud/bigquery/magics/line_arg_parser/parser.py         214      0     68      0   100%
google/cloud/bigquery/magics/line_arg_parser/visitors.py        85      0     22      0   100%
google/cloud/bigquery/magics/magics.py                         264      0     99      0   100%
google/cloud/bigquery/model.py                                 197      0     34      0   100%
google/cloud/bigquery/opentelemetry_tracing.py                  59      0     26      0   100%
google/cloud/bigquery/query.py                                 364      0    100      0   100%
google/cloud/bigquery/retry.py                                  23      0      4      0   100%
google/cloud/bigquery/routine/__init__.py                        8      0      0      0   100%
google/cloud/bigquery/routine/routine.py                       286      0     54      0   100%
google/cloud/bigquery/schema.py                                154      0     64      0   100%
google/cloud/bigquery/standard_sql.py                          162      0     50      0   100%
google/cloud/bigquery/table.py                                 934      0    310      0   100%
google/cloud/bigquery/version.py                                 1      0      0      0   100%
tests/unit/__init__.py                                           0      0      0      0   100%
tests/unit/_helpers/__init__.py                                  0      0      0      0   100%
tests/unit/_helpers/test_from_json.py                           22      0      0      0   100%
tests/unit/conftest.py                                          27      0      4      0   100%
tests/unit/helpers.py                                           32      0      0      0   100%
tests/unit/job/__init__.py                                       0      0      0      0   100%
tests/unit/job/helpers.py                                       84      0     20      0   100%
tests/unit/job/test_base.py                                    713      0      2      0   100%
tests/unit/job/test_copy.py                                    258      0     10      0   100%
tests/unit/job/test_extract.py                                 238      0     10      0   100%
tests/unit/job/test_load.py                                    505      0     36      0   100%
tests/unit/job/test_load_config.py                             526      0      0      0   100%
tests/unit/job/test_query.py                                  1139      0     54      0   100%
tests/unit/job/test_query_config.py                            189      0      0      0   100%
tests/unit/job/test_query_pandas.py                            444      0     20      0   100%
tests/unit/job/test_query_stats.py                             324      0      0      0   100%
tests/unit/line_arg_parser/__init__.py                           0      0      0      0   100%
tests/unit/line_arg_parser/test_lexer.py                        12      0      0      0   100%
tests/unit/line_arg_parser/test_parser.py                      101      0      0      0   100%
tests/unit/line_arg_parser/test_visitors.py                     13      0      0      0   100%
tests/unit/model/__init__.py                                     0      0      0      0   100%
tests/unit/model/test_model.py                                 178      0      0      0   100%
tests/unit/model/test_model_reference.py                        72      0      0      0   100%
tests/unit/routine/__init__.py                                   0      0      0      0   100%
tests/unit/routine/test_remote_function_options.py              59      0      0      0   100%
tests/unit/routine/test_routine.py                             193      0      0      0   100%
tests/unit/routine/test_routine_argument.py                     47      0      0      0   100%
tests/unit/routine/test_routine_reference.py                    72      0      0      0   100%
tests/unit/test__helpers.py                                    729      0      6      0   100%
tests/unit/test__http.py                                        95      0      2      0   100%
tests/unit/test__job_helpers.py                                104      0      4      0   100%
tests/unit/test__pandas_helpers.py                             643      0     50      0   100%
tests/unit/test__pyarrow_helpers.py                             12      0      0      0   100%
tests/unit/test__versions_helpers.py                           131      0      0      0   100%
tests/unit/test_client.py                                     3866      0    108      0   100%
tests/unit/test_create_dataset.py                              232      0      0      0   100%
tests/unit/test_dataset.py                                     777      0     22      0   100%
tests/unit/test_dbapi__helpers.py                              231      0     16      0   100%
tests/unit/test_dbapi_connection.py                            142      0      6      0   100%
tests/unit/test_dbapi_cursor.py                                442      0     18      0   100%
tests/unit/test_dbapi_types.py                                  26      0      0      0   100%
tests/unit/test_delete_dataset.py                               36      0      0      0   100%
tests/unit/test_encryption_configuration.py                     75      0      0      0   100%
tests/unit/test_external_config.py                             450      0      0      0   100%
tests/unit/test_format_options.py                               35      0      0      0   100%
tests/unit/test_job_retry.py                                   110      0     18      0   100%
tests/unit/test_legacy_types.py                                 13      0      0      0   100%
tests/unit/test_list_datasets.py                                47      0      2      0   100%
tests/unit/test_list_jobs.py                                   100      0      6      0   100%
tests/unit/test_list_models.py                                  39      0      2      0   100%
tests/unit/test_list_projects.py                                47      0      2      0   100%
tests/unit/test_list_routines.py                                39      0      2      0   100%
tests/unit/test_list_tables.py                                  76      0      4      0   100%
tests/unit/test_magics.py                                     1069      0     14      0   100%
tests/unit/test_opentelemetry_tracing.py                       131      0      4      0   100%
tests/unit/test_packaging.py                                    16      0      0      0   100%
tests/unit/test_query.py                                       838      0      4      0   100%
tests/unit/test_retry.py                                        76      0      0      0   100%
tests/unit/test_schema.py                                      436      0      8      0   100%
tests/unit/test_signature_compatibility.py                      27      0      0      0   100%
tests/unit/test_standard_sql_types.py                          260      0      0      0   100%
tests/unit/test_table.py                                      2784      0    134      0   100%
tests/unit/test_table_arrow.py                                  18      0      4      0   100%
tests/unit/test_table_pandas.py                                 88      0      2      0   100%
--------------------------------------------------------------------------------------------------------
TOTAL                                                        27251      1   2797      1    99%
Coverage failure: total of 99 is less than fail-under=100
nox > Command coverage report --show-missing --fail-under=100 failed with exit code 2
nox > Session cover failed.
```

Just so you know, you can see a rundown of all test results if you scroll down to the bottom of the logs:
image

**Comment by Gaurang033** [comment]
> Hi @Gaurang033, thank you so much for your contribution, we really appreciate it. I took a look at the log, and it seems coverage test is failing. Seeing from the log, line 521 in `google/cloud/bigquery/_pandas_helpers.py` wasn't run during unit tests. We probably need to make some changes to the unit test to ensure this line is covered. Usually, we require 100% unit test coverage for any commit to merge. If you need any help doing it, I'm more than willing to help.
> 
> ```
> nox > coverage report --show-missing --fail-under=100
> Name                                                         Stmts   Miss Branch BrPart  Cover   Missing
> --------------------------------------------------------------------------------------------------------
> google/cloud/bigquery/_helpers.py                              291      0    152      0   100%
> google/cloud/bigquery/_http.py                                  16      0      0      0   100%
> google/cloud/bigquery/_job_helpers.py                           94      0     20      0   100%
> google/cloud/bigquery/_pandas_helpers.py                       360      1    193      1    99%   521
> google/cloud/bigquery/_pyarrow_helpers.py                       27      0      4      0   100%
> google/cloud/bigquery/_tqdm_helpers.py                          55      0     20      0   100%
> google/cloud/bigquery/_versions_helpers.py                      76      0     20      0   100%
> google/cloud/bigquery/client.py                                855      0    318      0   100%
> google/cloud/bigquery/dataset.py                               383      0     95      0   100%
> google/cloud/bigquery/dbapi/__init__.py                         30      0      0      0   100%
> google/cloud/bigquery/dbapi/_helpers.py                        170      0     96      0   100%
> google/cloud/bigquery/dbapi/connection.py                       37      0     14      0   100%
> ... ...
> --------------------------------------------------------------------------------------------------------
> TOTAL                                                        27251      1   2797      1    99%
> Coverage failure: total of 99 is less than fail-under=100
> nox > Command coverage report --show-missing --fail-under=100 failed with exit code 2
> nox > Session cover failed.
> ```
> 
> Just to make it more efficient for you in the future, you can see a rundown of all test results if you scroll down to the bottom of the logs (kokoro test especially): image

I am running coverge using following, however my result different then I see in logs. 
`nox -R -s unit-3.8
 nox -s cover
`

**Comment by Linchin** [comment]
Thank you @Gaurang033 for fixing the coverage test :) 
LGTM

**Review by Linchin — APPROVED** [review]

**Pull request merged**
