### PR TITLE
ci: use python3 instead of python3.6 in build.sh

### PR DESCRIPTION
**Pull request by busunkim96**

### CODE REVIEW

**Comment by tswast** [comment]
Looks like `docs-presubmit` is trying to run the default nox sessions. I sent internal CL 348695855 to add NOX_SESSION to the allowed env vars.

**Comment by busunkim96** [comment]
docs-presubmit is now properly running just the docs jobs.

**Comment by plamut** [comment]
I see the _"no python3.6 error"_ is now gone, but the docs check now fails with a different error - is that in scope of this PR, too?

(FWIW, the `docfx` nox session succeeds locally)

**Comment by busunkim96** [comment]
@plamut I opened #423 and this PR to properly split off docfx (not run it in required check `Kokoro` build since it will fail and block merge). We're tracking the  `docfx` failure in https://github.com/googleapis/doc-templates/issues/94.

**Review by tswast — APPROVED** [review]

**Pull request merged**
