### PR TITLE
fix: Do not set job timeout extra property if None

### PR DESCRIPTION
**Pull request by bmwant**
### Description
`job_timeout_ms` declared as optional ([see docs](https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.job.CopyJobConfig#google_cloud_bigquery_job_CopyJobConfig_job_timeout_ms)), but setting it as None results in error:
```
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/my-bq-project/jobs?prettyPrint=false: Invalid value at 'job.configuration.job_timeout_ms.value' (TYPE_INT64), "None"

Location: None
Job ID: 5f5bf5bd-dc77-7eda-a2d3-69420a6bf6d6
 [{'@type': 'type.googleapis.com/google.rpc.BadRequest', 'fieldViolations': [{'field': 'job.configuration.job_timeout_ms.value', 'description': 'Invalid value at \'job.configuration.job_timeout_ms.value\' (TYPE_INT64), "None"'}]}]
```

because of [allowing None](https://github.com/googleapis/python-bigquery/blob/main/google/cloud/bigquery/job/base.py#L215), but not handling it properly. This fix doesn't cast None to a string in setter. Getter still works as expected, but we do not send invalid value in remote call.

### Simple script to reproduce
```python
from typing import Optional

from google.cloud import bigquery

query = "SELECT * FROM `project.table` LIMIT 1"
client = bigquery.Client()
config = bigquery.QueryJobConfig(use_query_cache=True, allow_large_results=True)
my_timeout: Optional[int] = None
config.job_timeout_ms = my_timeout
client.query(query, job_config=config)
```

### CODE REVIEW

**Comment by bmwant** [comment]
@Linchin updated, could you review?

**Comment by bmwant** [comment]
@Linchin rebased on the latest main branch

**Comment by Linchin** [comment]
Thank you for making the contribution and fix this bug for us! I wonder if you would like to lint the code, as this seems to be the only test that's failing. I haven't had the time to do it. To lint you need to install nox and run `nox -s lint` in the repo.

**Comment by bmwant** [comment]
Fixed linting, you can re-run checks now

**Review by Linchin — APPROVED** [review]
LGTM

**Pull request merged**
