### PR TITLE
deps: support Pythons <4

### LINKED ISSUE #1412: Support Pythons <4
I'd like to be able to allow python <4 in ibis, but as of this PR (https://github.com/ibis-project/ibis/pull/4797) I cannot due to this library's `<3.11` pin.

### PR DESCRIPTION
**Pull request by cpcloud**
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1412 🦕

### CODE REVIEW

**Comment by cpcloud** [comment]
cc @tswast

**Comment by tswast** [comment]
@cpcloud I'm looking into this. It would be a departure from most of the other Google client libraries. Would you mind sharing some of the reasoning here why it's important to have a wider upper bound?

I assume partially it's so it's easier to test with prerelease versions of Python?

**Comment by cpcloud** [comment]
@tswast The main reason is for testing new Python versions not necessarily pre-release only though, since 3.11 has been out for about a month.

**Comment by cpcloud** [comment]
Should I put `fix:` prefix so that a release will be cut?

**Comment by cpcloud** [comment]
Seems the CLA check is failing, but I have signed one according to the link.

**Comment by chalmerlowe** [comment]
GH associated my gmail account with the change and NOT my google account and despite being a Googler and having my google address associated with my GH account, the CLA check only sees that chalmer.lowe@gmail.com made the suggested change and co-authored a minor tweak. I am looking into how to reset the author on that change I suggested so that we can get past the CLA problem.
Sigh.

**Comment by cpcloud** [comment]
@chalmerlowe I went ahead and squashed it down to just myself as the author.

**Comment by chalmerlowe** [comment]
> @chalmerlowe I went ahead and squashed it down to just myself as the author.

sweet. thanks.
once the tests pass, I will merge the change.

**Comment by tswast** [comment]
> Should I put fix: prefix so that a release will be cut?

I think that'd be appropriate. I recall that `deps` will also show up in the changelog, so should also trigger a release.

**Review by chalmerlowe — APPROVED** [review]
LGTM

**Comment by cpcloud** [comment]
Thanks y'all!

**Comment by kevinfgordon** [comment]
@cpcloud thank you for this adjustment, I ran into the same issue trying to leverage this with 3.11 today.  Eagerly awaiting the release to be completed. 
FYI:  The readme still references < 3.11 incase that should be adjusted to reflect the new change.

**Pull request merged**
