### PR TITLE
fix: fix invalid version specification of pyarrow

### LINKED ISSUE #1402: Invalid version specification in setup.py
The version specification of pyarrow seems not to fulfill [PEP 440 (Version Identification and Dependency Specification)](https://peps.python.org/pep-0440/). I think it's a typo.

https://github.com/googleapis/python-bigquery/blob/929276949244f704688837dfca35cb7dacd44623/setup.py#L54

Due to this designation, some tools (e.g. [Poetry](https://python-poetry.org/)) detect it and fail when installing and/or locking packages.

### PR DESCRIPTION
**Pull request by mamo3gr**
Make version specification of pyarrow fulfill [PEP404](https://peps.python.org/pep-0440/).

- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #1402 🦕

### CODE REVIEW

**Review by aribray — APPROVED** [review]

**Comment by mamo3gr** [comment]
@aribray @chalmerlowe There seems to be something wrong with the build process. Could you tell me how to rerun kokoro in this PR and/or debug it on my local computer? I cherry-picked some commits from the main branch and they might solve the problem.

Many thanks for considering my request.

**Comment by chalmerlowe** [comment]
@mamo3gr

we have been doing some other changes in other PRs related to pyarrow, etc.
let me take a look at this PR and make sure everything lines up.

**Comment by chalmerlowe** [comment]
@mamo3gr @tswast 

Looking at the the current file on `main`, it looks like `pyarrow` was moved out of the `extras` category at some point and was listed as a simple dependency: https://github.com/googleapis/python-bigquery/blob/main/setup.py

Am I missing something? Is this PR still relevant?

**Comment by tswast** [comment]
@chalmerlowe Note that this is targeting the v1 branch. We have intentionally kept that branch alive for potential support for high priority fixes. Up to us if this qualifies.

**Pull request merged**
