### PR TITLE
fix: remove default timeout

### LINKED ISSUE #970: Python to construct CASE WHEN update SQL statement
I try to update 2K rows in BQ 

```
def update_bq_ads_status_failed(self, update_ads):
        affected_rows = 0
        for update_ads_chunk in split(update_ads, _UPDATE_CHUNK_SIZE):
            ad_ids = [item["ad_id"] for item in update_ads_chunk]
            removal_errors = [item["removal_error"] for item in update_ads_chunk]

            update_removal_error = ""
            for ad_id, removal_error in zip(ad_ids, removal_errors):
                update_removal_error = update_removal_error + \
                                       f''' WHEN ad_id = '{ad_id}' Then '{removal_error}' '''
            affected_rows += self.update_bq_ads_status(f"""
                            UPDATE '{table_full_name}' 
                            SET status = 'Failed Removing'  
                SET removal_error = CASE {update_removal_error} END 
                WHERE ad_id IN {str(ad_ids)}
                """)
        return affected_rows
```

I'm getting this error. I know it's too vague and not possible to debug like this.

> timeout=300.0, headers={'X-Server-Timeout': '300.0',
> 'Accept-Encoding': 'gzip', 'Content-Type': 'application/json',
> 'X-Goog-API-Client': 'gl-python/3.8.10 grpc/1.39.0 gax/2.0.0
> gapic/2.26.0 gccl/2.26.0', 'User-Agent': 'gl-python/3.8.10 grpc/1.39.0
> gax/2.0.0 gapic/2.26.0 gccl/2.26.0'})), last exception: ('Connection
> aborted.', RemoteDisconnected('Remote end closed connection without
> response'))

I'm trying to eliminate errors. Is my BQ update syntactically correct? 

What's the BQ update timeout?

### PR DESCRIPTION
**Pull request by tswast**
Internal folks, see: go/microgenerator-retries

> "Methods will **not** hedge by default." (emphasis mine)

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #970 🦕

### CODE REVIEW

**Review by plamut — COMMENTED** [review]
Has this been confirmed internally as the root cause for the issue the user was facing?

The code change itself looks good.

**Comment by tswast** [comment]
SRE and API core teams recommends not setting default timeout. Client should still be able to set timeouts in the case when an operation needs to finish within a certain time or else fail.

**Comment by tswast** [comment]
In the internal go/microgenerator-retries document, default timeouts + retrying on timeout error is defined as a form of hedging, which is not supposed to happen in our clients.

**Comment by plamut** [comment]
Thanks for elaborating, let's merge it then.

**Review by plamut — APPROVED** [review]

**Pull request merged**
