### PR TITLE
fix: typo in legacy docs

### LINKED ISSUE #2036: Typo in legacy_proto_types.rst
The word "supported" is written as "uspported".

### PR DESCRIPTION
**Pull request by jeffqg**
Rewrite uspported -> supported.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #2036 🦕

### CODE REVIEW

**Comment by chalmerlowe** [comment]
Let's have Kokoro do its thing and see if we can get this approved.

**Review by chalmerlowe — APPROVED** [review]
LGTM

**Comment by chalmerlowe** [comment]
@jeffqg 

Thank you very much for submitting this fix. I appreciate the help.
If you are interested in working on another task, I would be happy to do what I can to facilitate.

Have a great day!

**Comment by jeffqg** [comment]
Thanks! I'm starting to use this API, so I'll try to address any issues I come across.

**Pull request merged**
